q0 = [100 0 100 0]; % INITIAL CONFIGURATION
xd = [0 100 1150 1]; % WANTED POSITIONAL STATE OF END EFFECTOR
qd = ikine(q0, xd) % THE OPERATIONAL STATE TO GET THE POSITIONAL STATE
xt = fkine(qd) % APPLY FORWARD KINEMATICS TO CHECK ANSWER